version: "3.9"
services:
  langflow:
    # Use the public Docker Hub image for Langflow instead of the GitHub
    # Container Registry version, which requires authentication and caused
    # deployment failures.
    image: langflowai/langflow:latest
    environment:
      - PORT=7860
    ports:
      - "7860:7860"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile  # rename Dockerfile.txt → Dockerfile, or adjust this line if you keep Dockerfile.txt
    environment:
      - PORT=${PORT_API}          # you’ll set PORT_API=3002 in Coolify
      - SUPABASE_URL=https://whxgflpvlbajudkhmgnq.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoeGdmbHB2bGJhanVka2htZ25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTUzODIsImV4cCI6MjA3MDY3MTM4Mn0.8Tesgmv0pT8F1XijqaKx8vDqHyRWt7Fp5EWn-kvCLjI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - OPENROUTER_HTTP_REFERER=${OPENROUTER_HTTP_REFERER}
      - OPENROUTER_TITLE=${OPENROUTER_TITLE}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - LANGFLOW_URL=${LANGFLOW_URL}
    ports:
      - "${PORT_API}:3002"        # host port → container port

  web:
    build: ./apps/web
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}  # set this to http://api:3002
    ports:
      - "${PORT_WEB}:3003"        # host port → container port
